version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldbpoly
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306

  mysqldbpoly:
    container_name: mysqldbpoly
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: polyclinic
      MYSQL_ROOT_PASSWORD: password

#  phpmyadmin:
#    image: phpmyadmin
#    restart: always
#    ports:
#      - 8080:80
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=mysqldbpoly
#      - PMA_USER=root
#      - PMA_PASSWORD=password